<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from "vue";

import { fetchEventById, fetchEvents } from "./api";
import EventDetail from "./components/EventDetail.vue";
import EventSummary from "./components/EventSummary.vue";
import EventsTable from "./components/EventsTable.vue";
import EventsToolbar from "./components/EventsToolbar.vue";

const events = ref([]);
const selectedEvent = ref(null);
const loadingEvents = ref(false);
const loadingDetail = ref(false);
const errorMessage = ref("");

const filters = reactive({
  severity: "",
  serviceName: "",
  limit: 50,
});

const pollIntervalMs = Number(import.meta.env.VITE_POLL_INTERVAL_MS || 10000);
let pollTimer = null;

const serviceOptions = computed(() => {
  const uniqueNames = new Set(events.value.map((event) => event.service_name));
  return Array.from(uniqueNames).sort((left, right) => left.localeCompare(right));
});

async function loadEvents() {
  loadingEvents.value = true;
  errorMessage.value = "";

  try {
    const data = await fetchEvents(filters);
    events.value = data;

    if (selectedEvent.value) {
      const stillExists = data.find((event) => event.id === selectedEvent.value.id);
      if (!stillExists) {
        selectedEvent.value = null;
      }
    }
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to load events";
  } finally {
    loadingEvents.value = false;
  }
}

async function selectEvent(event) {
  loadingDetail.value = true;
  errorMessage.value = "";

  try {
    selectedEvent.value = await fetchEventById(event.id);
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : "Failed to load event detail";
  } finally {
    loadingDetail.value = false;
  }
}

function updateFilters(nextFilters) {
  filters.severity = nextFilters.severity;
  filters.serviceName = nextFilters.serviceName;
  filters.limit = nextFilters.limit;
}

function startPolling() {
  stopPolling();
  pollTimer = window.setInterval(() => {
    loadEvents();
  }, pollIntervalMs);
}

function stopPolling() {
  if (pollTimer) {
    window.clearInterval(pollTimer);
    pollTimer = null;
  }
}

watch(
  () => ({ ...filters }),
  () => {
    loadEvents();
  },
  { deep: true },
);

onMounted(() => {
  loadEvents();
  startPolling();
});

onBeforeUnmount(() => {
  stopPolling();
});
</script>

<template>
  <div class="app-shell">
    <header class="hero">
      <div>
        <p class="eyebrow">SimOps</p>
        <h1>Operational events at a glance</h1>
        <p class="hero-copy">
          A lightweight frontend for browsing synthetic incidents generated by the simulator and
          stored by the backend.
        </p>
      </div>
      <div class="hero-status">
        <span class="status-dot"></span>
        Polling every {{ pollIntervalMs / 1000 }}s
      </div>
    </header>

    <p v-if="errorMessage" class="error-banner">{{ errorMessage }}</p>

    <EventsToolbar
      :filters="filters"
      :service-options="serviceOptions"
      :loading="loadingEvents"
      @update:filters="updateFilters"
      @refresh="loadEvents"
    />

    <EventSummary :events="events" />

    <main class="content-grid">
      <EventsTable
        :events="events"
        :loading="loadingEvents"
        :selected-event-id="selectedEvent?.id ?? ''"
        @select="selectEvent"
      />
      <EventDetail :event="selectedEvent" :loading="loadingDetail" />
    </main>
  </div>
</template>

